name: Release - Dry Run

on:
  push:
    branches-ignore:
      - v[0-9]+

jobs:
  release-dry-run:
    name: Release - Dry Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.1"
      - run: npm ci
      - run: |
          echo "Github ref: ${{ env.GITHUB_REF }}"
      - run: npx semantic-release@17.4.4 --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: semantic-release:*
