name: Release - Dry Run

on:
  push:
    branches-ignore:
      - v[0-9]+

jobs:
  release-dry-run:
    name: Release - Dry Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.1"
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@35d90c4a713487c48ff93473fdff93e8dc1469f3
      - run: npm ci
      - run: |
          echo "Github ref: ${{ env.GITHUB_REF_SLUG_CS }}"
      # - run: npx semantic-release@17.4.4 --dry-run
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     DEBUG: semantic-release:*
